Budget/urls.py
from django.urls import path
from . import views

app_name = "Budget"

urlpatterns = [
    path("<str:name>", views.index, name="index"),
    path("", views.landing_page, name="landing_page"),
    path("create/", views.create, name="create"),
    path("view/", views.view, name="view"),
    path("about/", views.about, name="about"),
    path("services/", views.services, name="services"),
    path('delete/<str:name>/', views.delete_todo_list, name='delete_todo_list'),
]

Register/urls.py
from django.urls import path
from . import views

app_name = 'Register'

urlpatterns = [
    path("login/", views.login_request, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
]

Site/urls.py
from django.contrib import admin
from django.urls import path, include
# from Register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    # path("register/", v.register, name="register"),
    path("", include("Budget.urls")),
    path("", include("Register.urls")),
]

Budget/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todolist", null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
        

class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    amount = models.FloatField(blank=True, null=True)
    needs = models.FloatField(blank=True, null=True)
    wants = models.FloatField(blank=True, null=True)
    savings = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.amount} {self.needs} {self.wants} {self.savings}"

Budget/forms.py
from django import forms

class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    

Budget/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import ToDoList, Item
from .forms import CreateNewList
from django.contrib import messages


# Create your views here.


def landing_page(request):
    return render(request, "Home/Landing_Page.html", {})


def index(request, name):
    # get the object based on the id
    ls = ToDoList.objects.get(name=name)   
    # checks if ToDoList objects exists for specific user
    if ls in request.user.todolist.all():
        if request.method == "POST":
            if request.POST.get("calculate"):
                amount = request.POST.get("amount")
                try:
                    # create a new item and calculate needs, wants, and savings
                    item = ls.item_set.create(amount=float(amount))
                    needs = float(amount) * 0.5
                    wants = float(amount) * 0.3
                    savings = float(amount) * 0.2
                    item.needs = needs
                    item.wants = wants
                    item.savings = savings
                    item.save()
                except ValueError:
                    print("Please enter a valid amount")
            # check if the delete button was pressed
            elif "item_id" in request.POST:
                item_id = request.POST.get("item_id")
                try:
                    # get the item and delete it
                    item = ls.item_set.get(id=item_id)
                    item.delete()
                except Item.DoesNotExist:
                    print("Item does not exist")
            else:
                print("Not Clicked")      
        # render the list.html template with the to-do list object
        return render(request, "Home/list.html", {"ls": ls})
    # render the view.html template if the to-do list object doesn't exist
    return render(request, "Home/view.html", {})


def create(request):
    # checks if you posting data to server
    if request.method == "POST":  
    # holds all the form data in a dictionary
        form = CreateNewList(request.POST)
    # checks if the form is valid
        if form.is_valid():
    # gets the cleaned data from the form
            n = form.cleaned_data["name"]
    # we then create a new ToDoList object with the above cleaned_data
            t = ToDoList(name=n)
    # saves the object to the databasew
            t.save()
    # for saving a ToDoList to the specific user now
            request.user.todolist.add(t)
            
        return HttpResponseRedirect("/%s" %t.name)

    else:
    # creates an instance of the form
        form = CreateNewList()
    return render(request, "Home/create.html", {"form": form})


def view(request):
    if request.user.is_authenticated:
        # Get all to-do lists for the current user
        todolists = request.user.todolist.all()
        if not todolists:
            # If the user has no to-do lists, redirect to the home page
            messages.info(request=request, message=f"You have no to-do lists. Please create one.")
            return redirect("/create/")
        else:
            # Render the view template with the to-do lists
            return render(request, "Home/view.html", {})
    else:
        # If the user is not authenticated, redirect to the login page
        return redirect("/login/")

def about(request):
    return render(request, "Home/about_us.html", {})

def services(request):
    return render(request, "Home/services.html", {})

def delete_todo_list(request, name):
    # Get the to-do list object based on the name
    todo_list = ToDoList.objects.get(name=name)

    # Check if the user has permission to delete this to-do list
    if todo_list in request.user.todolist.all():
        # Delete the to-do list object
        todo_list.delete()
        # Redirect the user to the view page
        return redirect("/view/")
    else:
        # Return an error message
        return HttpResponse("You do not have permission to delete this to-do list.")

Budget/templates/Home/includes/Navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">B<small>udgetit</small></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'Budget:landing_page' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Budget:services' %}">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Budget:about' %}">About Us</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Budget:create' %}">Try<i class="bi bi-arrow-up-right" style="font-size: 10px;"></i></a>
          </li>
          <div class="active"></div>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Register:register' %}">Try<i class="bi bi-arrow-up-right" style="font-size: 10px;"></i></a>
          </li>
          <div class="active"></div>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">{{user.username}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Register:logout' %}">Log Out</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Register:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Register:register' %}">Sign Up</a>
            </li>
        </ul>
        {% endif %}
      </div>
    </div>
</nav>
  

{% comment %} <script>
  const navItems = document.querySelectorAll('.nav-item');
  navItems.forEach((item) => {
    item.addEventListener('click', () => {
      navItems.forEach((nav) => {
        nav.classList.remove('active');
      });
      item.classList.add('active');
    });
  });
</script> {% endcomment %}