Budget/urls.py
from django.urls import path
from . import views

app_name = "Budget"

urlpatterns = [
    path("<str:name>", views.index, name="index"),
    path("", views.landing_page, name="landing_page"),
    path("create/", views.create, name="create"),
    path("view/", views.view, name="view"),
    path("about/", views.about, name="about"),
    path("services/", views.services, name="services"),
    path('delete/<str:name>/', views.delete_todo_list, name='delete_todo_list'),
]

Site/urls.py
from django.contrib import admin
from django.urls import path, include
# from Register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    # path("register/", v.register, name="register"),
    path("", include("Budget.urls")),
    path("", include("Register.urls")),
]

Budget/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todolist", null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
        

class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    amount = models.FloatField(blank=True, null=True)
    needs = models.FloatField(blank=True, null=True)
    wants = models.FloatField(blank=True, null=True)
    savings = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.amount} {self.needs} {self.wants} {self.savings}"

Budget/forms.py
from django import forms

class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    

Budget/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import ToDoList, Item
from .forms import CreateNewList
from django.contrib import messages


# Create your views here.


def landing_page(request):
    return render(request, "Home/Landing_Page.html", {})


def index(request, name):
    # get the object based on the id
    ls = ToDoList.objects.get(name=name)   
    # checks if ToDoList objects exists for specific user
    if ls in request.user.todolist.all():
        if request.method == "POST":
            if request.POST.get("calculate"):
                amount = request.POST.get("amount")
                try:
                    # create a new item and calculate needs, wants, and savings
                    item = ls.item_set.create(amount=float(amount))
                    needs = float(amount) * 0.5
                    wants = float(amount) * 0.3
                    savings = float(amount) * 0.2
                    item.needs = needs
                    item.wants = wants
                    item.savings = savings
                    item.save()
                except ValueError:
                    print("Please enter a valid amount")
            # check if the delete button was pressed
            elif "item_id" in request.POST:
                item_id = request.POST.get("item_id")
                try:
                    # get the item and delete it
                    item = ls.item_set.get(id=item_id)
                    item.delete()
                except Item.DoesNotExist:
                    print("Item does not exist")
            else:
                print("Not Clicked")      
        # render the list.html template with the to-do list object
        return render(request, "Home/list.html", {"ls": ls})
    # render the view.html template if the to-do list object doesn't exist
    return render(request, "Home/view.html", {})


def create(request):
    # checks if you posting data to server
    if request.method == "POST":  
    # holds all the form data in a dictionary
        form = CreateNewList(request.POST)
    # checks if the form is valid
        if form.is_valid():
    # gets the cleaned data from the form
            n = form.cleaned_data["name"]
    # we then create a new ToDoList object with the above cleaned_data
            t = ToDoList(name=n)
    # saves the object to the databasew
            t.save()
    # for saving a ToDoList to the specific user now
            request.user.todolist.add(t)
            
        return HttpResponseRedirect("/%s" %t.name)

    else:
    # creates an instance of the form
        form = CreateNewList()
    return render(request, "Home/create.html", {"form": form})


def view(request):
    if request.user.is_authenticated:
        # Get all to-do lists for the current user
        todolists = request.user.todolist.all()
        if not todolists:
            # If the user has no to-do lists, redirect to the home page
            messages.info(request=request, message=f"You have no to-do lists. Please create one.")
            return redirect("/create/")
        else:
            # Render the view template with the to-do lists
            return render(request, "Home/view.html", {})
    else:
        # If the user is not authenticated, redirect to the login page
        return redirect("/login/")

def about(request):
    return render(request, "Home/about_us.html", {})

def services(request):
    return render(request, "Home/services.html", {})

def delete_todo_list(request, name):
    # Get the to-do list object based on the name
    todo_list = ToDoList.objects.get(name=name)

    # Check if the user has permission to delete this to-do list
    if todo_list in request.user.todolist.all():
        # Delete the to-do list object
        todo_list.delete()
        # Redirect the user to the view page
        return redirect("/view/")
    else:
        # Return an error message
        return HttpResponse("You do not have permission to delete this to-do list.")

Budget/templates/Home/Landing_Page.html
{% extends "Home/header.html" %}

{% block title %} Home {% endblock %}


{% block content %}
{% load static %}

{% if messages %}
<div style="display: flex; float: left; padding-top: 20px;">
    <ul class="messages-swipe" style="color: #EBEBF0;">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="color: white;"">{{ message }}</li>
        {% endfor %}
    </ul>
</div>
<script>
    setTimeout(function() {
        document.querySelector('.messages-swipe').style.display = 'none';
    }, 5000);
</script>
{% endif %}
<div class="body-center">
    <div class="budget-text">BUDGET</div>
    <div>
        <img class="bg-img" src="{% static 'design/images/mobile2.jpg' %}"/>
    </div>
    <div class="it-text">IT</div>
    <div class="slogan-container">
        <div class="slogan-text">
          Budget your monthly allowance, income and side hustle with our analytic system using the 50/30/20 rule
        </div>
    </div>

</div>
    
{% endblock %}

Budget/templates/Home/about_us.html
{% extends "Home/header.html" %}

{% block title %} About Us {% endblock %}


{% block content %}
{% load static %}

<div class="about-us-container">
    <img class="about-us-img" src="{% static 'design/images/about-us-bg2.jpg' %}" alt="about-us-image">
    <div>
        <p>
            <b class="about-us-heading">Welcome to our website!</b><br/>
            <small style="font-size: 11px;">We're here to help you stay on top of your finances and achieve your financial goals.</small><br/><br/>
            <p class="about-inner-paragraph">
                    Our website calculates your monthly budget using the 50/30/20 rule, a popular and effective method for managing your money.<br/>
                    With this rule, you allocate 50% of your income to your needs (such as rent, groceries, and bills), 30% to your wants (such as dining out and entertainment), and 20% to your savings or debt payments.<br/>
                <p class="about-inner-paragraph">
                    This balanced approach ensures that you have enough for your essentials, while still allowing you to enjoy your life and build your wealth.</br>
                    Our goal is to help you make smarter financial decisions and achieve your long-term goals. We believe that everyone can benefit from good money management, and we're here to make it easy and accessible for you.<br/>
                    Thank you for using our website, and we hope you enjoy our service!
                </p>
            </p>
        </p>
    </div>
</div>
    
{% endblock %}

Budget/templates/Home/create.html
{% extends "Home/header.html" %}


{% block title %} Create List {% endblock %}


{% block content %}
{% load static %}

{% if messages %}
<div class="messages-block">
    <ul class="messages-swipe" style="color: white;">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="color: white;"">{{ message }}</li>
        {% endfor %}
    </ul>
</div>
<script>
    setTimeout(function() {
        document.querySelector('.messages-swipe').style.display = 'none';
    }, 5000);
</script>
{% endif %}

<form method="post" action="/create/" class="create-form-container">

   {% csrf_token %}

   <div class="create-heading">
      <h1 class="create-heading-text">Create List</h1>
   </div>

   <div class="create-form">
      <div>
         {{ form }}
      </div>
      <button class="btn btn-primary create-button" type="submit", name="save">Create New</button>
   </div>

   <div class="view-message-container">
      <p>Please <a href="{% url 'Budget:view' %}" class="view-message"> click here </a> to access your past calculations...</p>
   </div>

</form>
    
{% endblock %}

Budget/templates/Home/header.html
<html>
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} BUDGET IT {% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'design/css/custom.css' %}" />
        <link rel="shortcut icon" type="image/png" href="{% static 'design/images/budgeit.ico' %}" />
    </head>
    <body style="background-color: #1F1F29">
        {% include "Home/includes/Navbar.html" %}
        <div>
            {% block content %}
            {% endblock %}   
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>
</html>

Budget/templates/Home/list.html
{% extends "Home/header.html" %}

{% block title %} View Calculations {% endblock %}

{% block content %}
{% load static %}

<form class="list-form-container" method="post" action="#">
    
    {% csrf_token %}

    <h1 style="color: white;">{{ ls.name }}</h1>

    <p>Enter amount: <input type="number" name="amount" step="0.01" /></p>

    <ul>
        {% for item in ls.item_set.all %}
            <li class="list-calculations">
                <p>Amount: ${{ item.amount }} | Needs: ${{ item.needs }} | Wants: ${{ item.wants }} | Savings: ${{ item.savings }}
                    <button type="submit" class="btn btn-danger" name="item_id" value="{{ item.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-x" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6.146 8.146a.5.5 0 0 1 .708 0L8 9.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 10l1.147 1.146a.5.5 0 0 1-.708.708L8 10.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 10 6.146 8.854a.5.5 0 0 1 0-.708z"/>
                            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                        </svg>
                        Delete
                    </button>
                </p>
            </li>
        {% endfor %}
    </ul>
    
    <div class="list-cta-btns">
        <input type="submit" name="calculate" value="Calculate" class="btn btn-primary calculate-btn"/>
        <button class="btn btn-danger go-bck-btn">
            <a href="{% url 'Budget:view' %}">Go Back</a>
        </button>
    </div>

</form>
{% endblock %}

Budget/templates/Home/services.html
{% extends "Home/header.html" %}

{% block title %} Services {% endblock %}


{% block content %}
{% load static %}

<div class="services-container">
    <img class="services-img" src="{% static 'design/images/about-us-bg4.jpg' %}" alt="about-us-image">
    <div>
        <p>
            <b class="services-heading">Our Services</b><br/>
            <small style="font-size: 11px;">We provide the following features:</small><br/><br/>
            <ul class="services-list">
                <li>Ability to create multiple budgets: Users can create budgets for different months or categories, and access them anytime.</li><br/>
                <li>Automated calculation of the 50/30/20 rule: The website does the calculation automatically and displays the results in real-time.</li><br/>
                <li>Visualization of budget breakdown: The website displays a graphical representation of how the budget is divided into needs, wants, and savings.</li><br/>
                <li>Reminder notifications: Users can set reminders for important dates such as when bills are due or when savings goals should be met.</li><br/>
                <li>Currency options: Users can choose the currency in which they want their budget to be displayed.</li><br/>
                <li>User account: Users can create an account and access their budgets from any device, as long as they are logged in.</li>
            </ul>
        </p>
    </div>
</div>

{% endblock %}

Budget/templates/Home/view.html
{% extends "Home/header.html" %}

{% block title %} View Lists {% endblock %}

{% block content %}
{% load static %}

    {% for td in user.todolist.all %}
    
    <div class="center card">
        <div class="card-body">
          <h5 class="card-title">
            <p>
              {{td.name}}
            </p>
          </h5>
          <p class="card-text">Check out your budget calculations for this month...</p>
          <form class="d-flex" method="post" action="{% url 'Budget:delete_todo_list' td.name %}">
            {% csrf_token %}
            <a href="/{{td.name}}" class="btn btn-primary" style="color: #EBEBF0; background: grey; border: none;">Go</a>
            <input style="margin: auto;" class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
    </div>

    {% endfor %}

{% endblock %}